base/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('products/', include('products.urls')),
    path('qna/', include('qna.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    import debug_toolbar

    # DDT 를 위한 설정
    urlpatterns += [
        path('__debug__/', include(debug_toolbar.urls)),
    ]

    # 미디어 파일
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path

from products import views

app_name = 'products'

urlpatterns = [
    path('', views.product_list, name='list'),
    path('<int:id>/', views.product_detail, name='detail'),
]

qna/urls.py
from django.urls import path

from qna import views

app_name = 'qna'

urlpatterns = [
    path('create_question', views.create_question, name='create_question')
]

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class User(AbstractUser):
    class GenderChoices(models.TextChoices):
        MALE = "M", "남성"
        FEMALE = "F", "여성"

    gender = models.CharField('성별', max_length=1, blank=True, choices=GenderChoices.choices)
    avatar = models.ImageField('아바타', blank=True, upload_to="accounts/avatar/%Y/%m/%d",
                               help_text="100px * 100px 크기의 gif/png/jpg 이미지를 업로드해주세요.")

cart/models.py
from django.db import models

# Create your models here.

markets/models.py
from django.db import models

# Create your models here.
from accounts.models import User


class Market(models.Model):
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    update_date = models.DateTimeField('갱신날짜', auto_now=True)
    name = models.CharField('마켓이름', max_length=100)
    site_url = models.URLField('마켓사이트URL', max_length=100)
    email = models.EmailField('마켓대표이메일', max_length=100)
    master = models.OneToOneField(User, on_delete=models.CASCADE)

products/models.py
from django.db import models

# Create your models here.
from markets.models import Market


class Product(models.Model):
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    update_date = models.DateTimeField('갱신날짜', auto_now=True)
    is_deleted = models.BooleanField('삭제여부', default=False)
    delete_date = models.DateTimeField('삭제날짜', null=True, blank=True)
    market = models.ForeignKey(Market, on_delete=models.DO_NOTHING)
    name = models.CharField('상품명(내부용)', max_length=100)
    display_name = models.CharField('상품명(고객용)', max_length=100)
    price = models.PositiveIntegerField('권장판매가')
    sale_price = models.PositiveIntegerField('실제판매가')
    is_hidden = models.BooleanField('노출여부', default=False)
    is_sold_out = models.BooleanField('품절여부', default=False)
    category_id = models.PositiveIntegerField('카테고리번호(추후설계)', default=0)
    hit_count = models.PositiveIntegerField('조회수', default=0)
    review_count = models.PositiveIntegerField('리뷰수', default=0)
    review_point = models.PositiveIntegerField('리뷰평점', default=0)


class ProductReal(models.Model):
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    update_date = models.DateTimeField('갱신날짜', auto_now=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="product_reals")
    option_1_type = models.CharField('옵션1 타입', max_length=10, default='SIZE')
    option_1_name = models.CharField('옵션1 이름(내부용)', max_length=50)
    option_1_display_name = models.CharField('옵션1 이름(고객용)', max_length=50)
    option_2_type = models.CharField('옵션2 타입', max_length=10, default='COLOR')
    option_2_name = models.CharField('옵션2 이름(내부용)', max_length=50)
    option_2_display_name = models.CharField('옵션2 이름(고객용)', max_length=50)
    option_3_type = models.CharField('옵션3 타입', max_length=10, default='', blank=True)
    option_3_name = models.CharField('옵션3 이름(내부용)', max_length=50, default='', blank=True)
    option_3_display_name = models.CharField('옵션3 이름(고객용)', max_length=50, default='', blank=True)
    is_sold_out = models.BooleanField('품절여부', default=False)
    is_hidden = models.BooleanField('노출여부', default=False)
    add_price = models.IntegerField('추가가격', default=0)
    stock_quantity = models.PositiveIntegerField('재고개수', default=0)  # 품절일때 유용함

qna/models.py
from django.contrib.contenttypes.fields import GenericForeignKey
from django.contrib.contenttypes.models import ContentType
from django.db import models

# Create your models here.
from accounts.models import User


class Question(models.Model):
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    update_date = models.DateTimeField('갱신날짜', auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    content_type = models.ForeignKey(ContentType, related_name="content_type_question", on_delete=models.DO_NOTHING)
    object_id = models.PositiveIntegerField('관련 데이터 번호')    # product면 무조건 상품이어야하지만 object는 범용성이 있기 때문에 object로 작성
    content_object = GenericForeignKey('content_type', 'object_id')
    body = models.TextField('내용')
    is_complete = models.BooleanField('답변완료여부', default=False)


class Answer(models.Model):
    reg_date = models.DateTimeField('등록날짜', auto_now_add=True)
    update_date = models.DateTimeField('갱신날짜', auto_now=True)
    question = models.OneToOneField(Question, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    body = models.TextField('내용')

accounts/views.py
from django.shortcuts import render

# Create your views here.

cart/views.py
from django.shortcuts import render

# Create your views here.

markets/views.py
from django.shortcuts import render

# Create your views here.

products/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import render, get_object_or_404

from products.models import Product


def product_list(request: HttpRequest):
    products = Product.objects.order_by('-id')

    return render(request, "products/product_list.html", {
        "products": products
    })


def product_detail(request: HttpRequest, id):
    product = get_object_or_404(Product, id=id)

    product_reals = product.product_reals.order_by()

    return render(request, "products/product_detail.html", {
        "product": product,
        "product_reals": product_reals,
    })

qna/views.py
from django.http import HttpRequest, HttpResponse


# Create your views here.
def create_question(request: HttpRequest):
    return HttpResponse("안녕")

base/templates/layout.html
<!doctype html>
{% load static %}
<html lang="ko">    <!-- en -> ko 로 수정 -->
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>메가쇼핑몰</title>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/css/bootstrap.min.css">
    <script defer src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.3/js/bootstrap.min.js"></script>

    <link rel="stylesheet" href="{% static 'common.css' %}">
    <script defer src="{% static 'common.js' %}"></script>
</head>
<body>
{% block content %}
{% endblock %}
</body>
</html>

products/templates/products/product_detail.html
{%block content %}
<section class="section-prod-detail mt-4">
    <div class="container">
        <h1>기본정보</h1>
        <div>
            번호 : {{product.id}}
        </div>
        <div>
            등록 : {{product.reg_date}}
        </div>
        <div>
            수정 : {{product.update_date}}
        </div>
        <div>
            이름 : {{product.display_name}}
        </div>
        <div>
            가격 : {{product.sale_price}}원
        </div>
        <div>
            마켓 : {{product.market.name}}
        </div>

        <h1 class="mt-3">옵션</h1>
        <ul>
            {% for product_real in product_reals %}
            <li>
                {{product_real.option_1_type}} : {{product_real.option_1_display_name}}
                /
                {{product_real.option_2_type}} : {{product_real.option_2_display_name}}
            </li>
            {% endfor %}
        </ul>

        <form method="POST" action="{% url 'qna:create_question' %}">
            {% csrf_token %}

            <div>
                <span>내용</span>
                <textarea name="body" rows="10"></textarea>
            </div>

            <div>
                <span>질문작성</span>
                <input type="submit" value="작성">
            </div>
        </form>
    </div>
</section>
{%endblock%}

products/templates/products/product_list.html
{% extends "layout.html" %}

{%block content %}
<section class="section-prod-list mt-4">
    <div class="container">
        <ul>
            {% for product in products %}
            <li><a href="{% url 'products:detail' product.id %}">{{product.id}} {{product.display_name}}
                {{product.sale_price}}원</a></li>
            {% endfor %}
        </ul>
    </div>
</section>
{%endblock%}